### ISSUE TITLE
Bouton Nouvelle Grossesse indispo dans formulaires consultation obs

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-modGynObs#11]
Bjr,

Sur la VM de demo, si on crée un RDV via Agenda (par exemple Betty KANE), en consult obst sur le jour en cours puis on va dans Praticien/Recherche (pour forcer la mise à jour des patients dans le menu Patients). Puis sélectionne le RDV à venir que l'on vient de créer dans le menu Patients, alors il n'y a de disponible que "Colposcopie" "Consultation dynécologique" et "Echographique Gynécologique" d'affiché. Pas de bouton "Nouvelle Grossesse" n'est affiché (ou de formulaire associé déjà ouvert). Le problème à lieu aussi quand on ouvre la consultation

Toutefois, le bouton s'affiche bien pour un dossier pré-existant ayant déjà une grossesse (par exemple /patient/3/ ).

Cdt,
JB

**Comment by MedShake** [comment]
Bonjour
Merci pour ce retour que je ne découvre que maintenant ! Nous passons peu souvent sur le site github.
Je vais regarder si le problème est reproductible sur la version 4 qui devait être finalisée d'ici peu.   

Bien cdt,

B.

**Comment by MedShake** [comment]
Re
Je crois qu'il n'y a pas de problème. Betty Kane à 63 ans dans la VM de démo ... le bouton nouvelle grossesse n'est donc pas affiché ! (Je n'ai pas trop compris l'histoire de faire des aller-retour pour "forcer" l'affichage. C'est du web, un petit reload de la page au pire, mais en théorie pas de manip à faire de plus).  

Bien cdt

B.

**Comment by bugeaud** [comment]
Merci pour ce retour.

Je mets en place une image à jour (tentative de docker) et je resterais sur cette base pour confirmer le problème. Au passage, le critère d'âge pour bloquer le bouton ne me semble pas pertinent : tout au plus si la patiente est ménoposée et n'a pas suivit de FIV on peut supposer qu'elle ne peut être enceinte... sauf miracle.

Cdt,
JB
