### ISSUE TITLE
Résumé du dossier avec erreur sur champ Rubéole

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-modGynObs#12]
Sur un dossier gyn, si on va sur Courriers & Certificats puis "Résumé dossier", le dossier ainsi généré contient une ligne indiqué :
"Sérologie rubéole : Toxo +"

La valeur qui devrait être affichée est : 
"Sérologie rubéole : Rub +"

**Comment by MedShake** [comment]
Bonjour

Merci pour ce signalement qui, comme pour l'autre, est de découverte tardive pour ce qui me concerne .... (Nous passons peu sur le site). 
J'avais repéré cette coquille il y a fort longtemps, mais visiblement je ne l'avais corrigée que sur nos versions en prod !!
Je viens de pousser la correction. 

Bien cdt,

B.
