### ISSUE TITLE
Ajout de tags pour Certificat de Grossesse

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-modGynObs#20]
Bonjour,

Dans les tags disponibles pour la génération, à la catégorie Grossesse, seul tag.DDR et tag.ddgReel semblent disponible.

Il faudrait pouvoir disposer en complément de tag.terme9mois afin de préciser la date prévue d'accouchement. Cette date est demandée par les employeurs des patientes.

Cdt
JB

**Comment by MedShake** [comment]
Bonjour
L'opération peut être réalisée dans le template twig simplement via date_modify
https://twig.symfony.com/doc/3.x/filters/date_modify.html

On peut aussi amender msModBaseCalcMed avec la bonne méthode et l'utiliser pour générer le tag dans msModGynobsDataCourrier (cf lignes 198 ou 211)

B.

**Comment by bugeaud** [comment]
Bonjour Bertrand,

Merci pour le retour. Le date modify semble le plus simple. Je vais vérifier s'il y a des impacts à ne pas utiliser le champ réel et à redériver de ddr /ddrReel.

Cdt,
JB
