### ISSUE TITLE
Méthode non déclarée en static dans la classe CalcMed

### ISSUE THREAD

**Issue by bugeaud** [MedShake/MedShakeEHR-modGynObs#22]
Bonjour,

Aprés mise à jour sur la dernier version à date, mon instance en prod retourne maintenant des erreurs dans gynobs type 

[Mon Dec 05 09:45:44.199711 2022] [php:error] [pid 24] [client 192.168.1.58:45072] PHP Fatal error:  Uncaught Error: Non-static method msModGynobsCalcMed::poids100() cannot be called statically in /app/MedShakeEHR-base/class/msModGynobsDataCourrier.php:243\nStack trace:\n#0 /app/MedShakeEHR-base/class/msCourrier.php(248): msModGynobsDataCourrier::type_e22poidsFA_CompleteData()\n#1 /app/MedShakeEHR-base/class/msPDF.php(428): msCourrier->getCrData()\n#2 /app/MedShakeEHR-base/class/msPDF.php(252): msPDF->_makeBody()\n#3 /app/MedShakeEHR-base/class/msPDF.php(222): msPDF->makePDF()\n#4 /app/MedShakeEHR-base/controlers/print/pdfShow.php(37): msPDF->makePDFfromObjetID()\n#5 /app/MedShakeEHR-base/public_html/index.php(140): include('...')\n#6 {main}\n  thrown in /app/MedShakeEHR-base/class/msModGynobsDataCourrier.php on line 243, referer: http://host/patient/2700/

Effectivement l'appel semble faire référence à une méthode statique qui ne l'est pas dans 
https://github.com/MedShake/MedShakeEHR-modGynObs/blob/master/class/msModGynobsCalcMed.php

Je pense qu'il faut ajouter static à cette méthode ...

Je ne comprend pas pour l'heure pourquoi ce problème ne se posait pas avant ...

++

**Comment by MedShake** [comment]
Alors ça, c'est un sacré mystère !
J'ai mergé. 
Je vais monter en version.
Merci !
